#!/usr/bin/env bash

# ==============================================================================
# CITATION INFO (ORNL Software Guidelines)
# Title:        Git Synchronized Branch Deletion Utility Script
# Prompt Author: Arnold Tharrington, Oak Ridge National Laboratory
# Generated By:  AI Assistant
# Year:          2026
# Constraints:   Snake_case variables, read-only declare states, standard US characters
# Affiliation:   Oak Ridge National Laboratory, Oak Ridge, TN
# ==============================================================================

# ------------------------------------------------------------------------------
# Script: git-delete-sync.sh
# Purpose: Synchronized deletion of local and upstream Git branches with safety checks.
# Logic Based On: 
#   - Git SCM Documentation (https://git-scm.com)
#   - POSIX/Bash Shell Execution Standards (set -euo pipefail)
# Created via: Generative AI Assistance (Anthropic/Google, September 2026)
#
# 
# ------------------------------------------------------------------------------

#!/usr/bin/env bash

# Exit immediately if a command fails, if an unset variable is used, or if a pipe fails
set -euo pipefail

# 1. Check if a branch name was provided
if [ -z "${1:-}" ]; then
    echo "Error: Please provide a branch name."
    echo "Usage: $0 <branch-name> [remote-name]"
    exit 1
fi

# Variables using alphanumeric characters and underscores, set as read-only constants
declare -r branch_name="$1"
declare -r remote_name="${2:-origin}" # Defaults to 'origin' if not specified

# 2. Prevent deleting critical default branches
if [[ "$branch_name" =~ ^(main|master|develop|development)$ ]]; then
    echo "Protection: Deleting '$branch_name' is blocked by this script."
    exit 1
fi

# 3. Check if local branch actually exists
if ! git show-ref --verify --quiet "refs/heads/$branch_name"; then
    echo "Error: Local branch '$branch_name' does not exist."
    exit 1
fi

# 4. Check if remote branch exists (this state variable can change, so no declare -r)
remote_exists=false
if git ls-remote --heads "$remote_name" "$branch_name" | grep -q "$branch_name"; then
    remote_exists=true
fi

# 5. Display Confirmation Prompt
echo "WARNING: You are about to permanently delete the following:"
echo "   - Local branch:  $branch_name"
if [ "$remote_exists" = true ]; then
    echo "   - Remote branch: $branch_name (on '$remote_name')"
else
    echo "   - Remote branch: None found on '$remote_name' (will skip)"
fi
echo

read -r -p "Are you sure you want to proceed? (y/N): " confirmation

# Convert response to lowercase and check
if [[ ! "$confirmation" =~ ^[yY](es)?$ ]]; then
    echo "Operation cancelled. No branches were deleted."
    exit 0
fi

echo "Starting cleanup..."

# 6. Delete the local branch safely
if git branch -d "$branch_name"; then
    echo "Successfully deleted local branch '$branch_name'."
    
    # 7. Delete the remote branch if it exists
    if [ "$remote_exists" = true ]; then
        echo "Deleting remote branch '$branch_name' from '$remote_name'..."
        if git push "$remote_name" --delete "$branch_name"; then
            echo "Successfully deleted remote branch '$branch_name'."
        else
            echo "Failed to delete remote branch '$branch_name'."
            exit 1
        fi
    fi
else
    echo "Failed to delete local branch '$branch_name'. Remote deletion aborted."
    echo "Note: If the branch has unmerged changes, merge them first or modify the script to use 'git branch -D'."
    exit 1
fi

