# ==============================================================================
# CITATION INFO (ORNL Software Guidelines)
# Title:        Git Feature Branch Deployment Protocol
# Repository:   arnoldt100
# Prompt Author: Arnold Tharrington, Oak Ridge National Laboratory
# Generated By:  AI Assistant
# Year:          2026
# Constraints:   Snake_case variables, read-only declare states, standard US characters
# Affiliation:   Oak Ridge National Laboratory, Oak Ridge, TN
# ==============================================================================

#!/usr/bin/env bash

# Exit immediately if a command fails, if an unset variable is used, or if a pipe fails
set -euo pipefail

# 1. Check if a feature name was provided
if [ -z "${1:-}" ]; then
    echo "Error: Please provide a feature branch name."
    echo "Usage: $0 <feature-name> [remote-name]"
    exit 1
fi

# Variables using alphanumeric characters and underscores, set as read-only constants
declare -r feature_suffix="$1"
declare -r remote_name="${2:-origin}" # Defaults to 'origin' if not specified
declare -r branch_name="feature/$feature_suffix"

# 2. Verify script is running inside a git repository
if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    echo "Error: This directory is not a valid Git repository."
    exit 1
fi

# 3. Check if local develop branch exists
if ! git show-ref --verify --quiet refs/heads/develop; then
    echo "Error: Local 'develop' branch does not exist."
    echo "Please create or fetch 'develop' before running this script."
    exit 1
fi

# 4. Check if the target feature branch already exists locally or remotely
if git show-ref --verify --quiet "refs/heads/$branch_name"; then
    echo "Error: Local branch '$branch_name' already exists."
    exit 1
fi

if git ls-remote --heads "$remote_name" "$branch_name" | grep -q "$branch_name"; then
    echo "Error: Remote branch '$branch_name' already exists on '$remote_name'."
    exit 1
fi

# 5. Display Confirmation Prompt
echo "WARNING: You are about to perform the following operations:"
echo "   - Switch to 'develop' and pull latest changes"
echo "   - Create and checkout new branch: $branch_name"
echo "   - Push '$branch_name' upstream to '$remote_name'"
echo

read -r -p "Are you sure you want to proceed? (y/N): " confirmation

# Convert response to lowercase and check
if [[ ! "$confirmation" =~ ^[yY](es)?$ ]]; then
    echo "Operation cancelled. No branches were created."
    exit 0
fi

echo "Starting deployment workflow..."

# 6. Switch to develop and update it
echo "Switching to develop..."
git checkout develop

echo "Pulling latest changes for develop..."
git pull "$remote_name" develop

# 7. Create and checkout the new feature branch
echo "Creating new local branch '$branch_name' off develop..."
git checkout -b "$branch_name"

# 8. Push the new branch upstream with tracking flags
echo "Pushing '$branch_name' upstream to '$remote_name'..."
if git push -u "$remote_name" "$branch_name"; then
    echo "Successfully created and pushed branch '$branch_name' upstream."
else
    echo "Failed to push branch '$branch_name' upstream."
    exit 1
fi

